apiVersion: v1
kind: Service
metadata:
  name: portfolio-nginx
  namespace: portfolio
  labels:
    app.kubernetes.io/name: portfolio-nginx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: portfolio-nginx
  ports:
    - name: http
      port: 80
      targetPort: http

