name: build-and-push

on:
  push:
    branches: ["main"]
    paths:
      - "k8s/**"
      - "site/**"
      - "Dockerfile"
      - ".github/workflows/build-and-push.yml"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push (sha + latest)
        env:
          ECR_REPOSITORY_URL: ${{ secrets.ECR_REPOSITORY_URL }}
          IMAGE_SHA_TAG: ${{ github.sha }}
        run: |
          docker build -t app:${IMAGE_SHA_TAG} .

          docker tag app:${IMAGE_SHA_TAG} ${ECR_REPOSITORY_URL}:${IMAGE_SHA_TAG}
          docker tag app:${IMAGE_SHA_TAG} ${ECR_REPOSITORY_URL}:latest

          docker push ${ECR_REPOSITORY_URL}:${IMAGE_SHA_TAG}
          docker push ${ECR_REPOSITORY_URL}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_CD_ROLE_ARN }}

      - uses: azure/setup-kubectl@v4

      - name: Configure kubectl (EKS)
        run: |
          aws eks update-kubeconfig --region us-east-1 --name projeto-eks-personal

      - name: Restart deployment to pull latest image
        run: |
          kubectl -n portfolio rollout restart deploy/portfolio-nginx
          kubectl -n portfolio rollout status deploy/portfolio-nginx --timeout=5m

